# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arounduaetest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Arounduaetest
  pod 'DropDown'
  pod 'Cosmos'
  pod 'KMPlaceholderTextView'
  pod 'ImageSlideshow'
  pod 'ImageSlideshow/SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'XLPagerTabStrip'
  pod 'NVActivityIndicatorView'
  pod 'RangeSeekSlider'
  pod 'DLRadioButton'
  pod 'Toast-Swift'
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'XLPagerTabStrip'
  pod 'GooglePlaces'
  pod 'CountryPickerSwift'
  pod 'FlagKit'
  pod 'DZNEmptyDataSet'

end
